name: env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - libgdal
  - gdal
  - proj
  - rasterio>=1.3.2
  - gcc_linux-64
  - gxx_linux-64
  - binutils_linux-64
  - libpq
  - git
  - wget
  - curl
  - unzip
  - htop
  - tmux
  - vim
  - rio-cogeo
  - access
  - aiobotocore
  - boto3
  - s5cmd
  - affine
  - aiohttp
  - aioitertools
  - aiosignal
  - astropy
  - async-timeout
  - attrs
  - Babel
  - blinker
  - boltons
  - Bottleneck
  - cachetools
  - cattrs
  - certifi
  - cftime
  - charset-normalizer
  - checksumdir
  - ciso8601
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - colour
  - cycler
  - cython
  - dask
  - dask-image
  - datadog
  - deepdiff
  - defusedxml
  - distributed>=2023.11
  - docutils
  - ephem
  - fiona
  - Flask
  - Flask-Babel
  - fonttools
  - frozenlist
  - fsspec
  - GeoAlchemy2
  - geopandas<1.0.0
  - greenlet
  - HeapDict
  - icu>=73.2
  - idna
  - imageio
  - importlib-metadata
  - importlib-resources
  - ipyleaflet
  - iso8601
  - itsdangerous
  - Jinja2
  - jmespath
  - jsonschema>4.18
  - kiwisolver
  - lark
  - python-lmdb
  - locket
  - lxml
  - MarkupSafe
  - matplotlib-base
  - morecantile
  - mpi4py
  - multidict
  - munch
  - netCDF4
  - networkx
  - nodejs
  - numexpr
  - numpy
  - ordered-set
  - packaging
  - pandas
  - partd
  - Pillow
  - PIMS
  - poetry
  - psutil
  - psycopg2
  - pyasn1
  - pydantic
  - pyerfa
  - pyparsing=2.4.7
  - pyproj
  - pyrsistent
  - pystac
  - pystac-client>=0.8.1
  - pytest!=8.1.0
  - python-dateutil
  - python-rapidjson
  - python-slugify
  - pytz
  - PyWavelets
  - PyYAML
  - rasterstats
  - regex
  - requests
  - requests-aws4auth
  - rsa
  - ruamel.yaml
  - ruamel.yaml.clib
  - s3transfer
  - scikit-image
  - scipy>=1.10.1
  - sentry-sdk
  - setuptools-scm
  - Shapely>=2.0
  - six
  - slicerator
  - snuggs
  - sortedcontainers
  - SQLAlchemy<2.0
  - statsmodels
  - structlog
  - tblib
  - text-unidecode
  - tifffile
  - tini
  - tomli
  - toolz
  - tornado
  - tqdm
  - typing_extensions
  - urllib3
  - urlpath
  - Werkzeug
  - wrapt
  - xarray>=2023.1.0
  - yarl
  - zict
  - zipp
  - zstandard
# misc
  - alabaster
  - dill
  - ffmpeg-python
  - param
  - pydash
  - s3fs
  - voluptuous
  - bottleneck
# Scientific Stack
  - gsl
  - cgal-cpp
  - boost
  - openmp
  - muparser
  - numba
  - dask-ml
  - pathos
  - scikit-learn
  - tensorflow>=2.16
  - xgboost
  - zarr
  - bokeh=3.2.2
  - descartes
  - matplotlib
  - seaborn
    # - pygeos
  - cmocean
  - gcsfs
  - geohash2
  - geojson
  - geopy
  - h5py
  - mapclassify
  - OWSLib
  - pandana
  - planetary-computer
  - protobuf
  - pysal
  - pysheds
  - python-geohash
  - rio-stac
  - rioxarray
  - rsgislib
  - Rtree
  - spyndex
  - urbanaccess
  - contextily
  - pyTMD<=2.1.0
  - xarray-spatial
# jupyter things
  - autopep8
  - black
  - python-jose
  - ecdsa
  - jupyter
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker
  - jupyterlab-code-snippets
  - jupyterlab-dash
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyterlab-github
  - jupyterlab_iframe
  - jupyterlab_widgets
  - jupyterlab-topbar
  - jupyterlab-system-monitor
  - jupyterhub
  - jupytext<1.16
  - jupyterlab_pygments<0.3.0
  - jupyter-resource-usage
  - jupyter_server
  - jupyter-server-proxy
  - jupyter-ui-poll
  - ipycanvas
  - ipycytoscape
  - ipyevents
  - ipyfilechooser
  - ipyleaflet
  - ipython
  - ipywidgets
  - isort
  - nbdime
  - nbgitpuller
  - mypy
  - prompt-toolkit # because of line_profiler/ipython
  - nbconvert # because of jupyter_contrib_nbextensions
  - nbformat
  - sidecar
  - yapf
  - jedi
  - parso
  - folium
  - ipympl
  - graphviz
  - plotly
  - pydotplus
  - dask-labextension
  - datashader
  - geoviews
  - holoviews
  - jupyter_bokeh
  - panel
  - pyviz_comms
# jupyterhub + dask
  - dask-gateway
# jupyterlab + language packages
  - jupyterlab-language-pack-fr-FR
