name: Vulnerability Scan

on:
  schedule:
    - cron: 07 7 * * * 

jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.0.8
        continue-on-error: true
        with:
          image-ref: "geoscienceaustralia/sandbox:latest"
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'